import { FULFILLED } from 'redux-promise-middleware';

export const GET_USER_COLLECTIONS = 'GET_USER_COLLECTIONS';
export const GET_USER_WISHLISTS = 'GET_USER_WISHLISTS';
export const GET_USER_AGG_METADATA = 'GET_USER_AGG_METADATA';
export const GET_USER_COLLECTIONS_FULFILLED = `${GET_USER_COLLECTIONS}_${FULFILLED}`;
export const GET_USER_WISHLISTS_FULFILLED = `${GET_USER_WISHLISTS}_${FULFILLED}`;
export const GET_USER_AGG_METADATA_FULFILLED = `${GET_USER_AGG_METADATA}_${FULFILLED}`;
export const CREATE_COLLECTION = 'CREATE_COLLECTION';
export const CREATE_COLLECTION_FULFILLED = `${CREATE_COLLECTION}_${FULFILLED}`;
export const ADD_GAME_TO_COLLECTION = 'ADD_GAME_TO_COLLECTION';
