export const OPEN_ADD_GAME_DIALOG = 'OPEN_ADD_GAME_DIALOG';
export const CLOSE_ADD_GAME_DIALOG = 'CLOSE_ADD_GAME_DIALOG';
export const CLOSE_ADD_TIMESHEET_DIALOG = 'CLOSE_ADD_TIMESHEET_DIALOG';
export const OPEN_ADD_TIMESHEET_DIALOG = 'OPEN_ADD_TIMESHEET_DIALOG';
