export const ADD_MSG_SNACKBAR = 'ADD_MSG_SNACKBAR';
export const DISPLAY_MSG_SNACKBAR = 'DISPLAY_MSG_SNACKBAR';
export const CLOSE_MSG_SNACKBAR = 'CLOSE_MSG_SNACKBAR';
export const CLEAR_MSG_SNACKBAR = 'CLEAR_MSG_SNACKBAR';
