import { FULFILLED } from 'redux-promise-middleware';

export const GET_GAME_COLLECTION_BY_USERID = 'GET_GAME_COLLECTION_BY_USERID';
export const GET_GAME_BY_ID = 'GET_GAME_BY_ID';
export const GET_GAME_BY_ID_FULFILLED = `${GET_GAME_BY_ID}_${FULFILLED}`;
export const GET_GAME_SCREENSHOTS_BY_ID = 'GET_GAME_SCREENSHOTS_BY_ID';
export const GET_GAME_SCREENSHOTS_BY_ID_FULFILLED = `${GET_GAME_SCREENSHOTS_BY_ID}_${FULFILLED}`;
export const GET_GAME_COVER_BY_ID = 'GET_GAME_COVER_BY_ID';
export const GET_GAME_COVER_BY_ID_FULFILLED = `${GET_GAME_COVER_BY_ID}_${FULFILLED}`;
export const GET_GAME_LINKS_BY_ID = 'GET_GAME_LINKS_BY_ID';
export const GET_GAME_LINKS_BY_ID_FULFILLED = `${GET_GAME_LINKS_BY_ID}_${FULFILLED}`;
export const GET_GAME_COLLECTION_BY_USERID_FULFILLED = `${GET_GAME_COLLECTION_BY_USERID}_${FULFILLED}`;
